sudo: false
language: python
python:
  - '2.7'
  - '3.4'
env:
  global:
    - DB=postgres
  matrix:
    - DJANGO=1.6.11
    - DJANGO=1.7.7
install:
  - pip install -q coverage flake8 Django==$DJANGO
before_script:
  - psql -c 'CREATE DATABASE activatable_model;' -U postgres
script:
  - flake8 .
  - coverage run setup.py test
  - coverage report --fail-under=100
