# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-28 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivatableModelWRelAndCascade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('rel_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tests.Rel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
